version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 99
    versioning-strategy: "increase"
